# Generated by Django 2.2.16 on 2022-05-15 13:14

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220514_0035'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_error',
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, validators=[reviews.validators.validate_year]),
        ),
    ]
